# Generated by Django 5.1.4 on 2024-12-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloggerArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("video", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("picture", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("click_num", models.IntegerField(default=0)),
                ("classify", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "blogger_article",
            },
        ),
        migrations.CreateModel(
            name="LifeFragments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("video", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("picture", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("click_num", models.IntegerField(default=0)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "life_fragments",
            },
        ),
        migrations.CreateModel(
            name="Philosophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("video", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("picture", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("click_num", models.IntegerField(default=0)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "philosophy",
            },
        ),
        migrations.CreateModel(
            name="Poetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("video", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("picture", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("click_num", models.IntegerField(default=0)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "poetry",
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("video", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("picture", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("click_num", models.IntegerField(default=0)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "programme",
            },
        ),
        migrations.CreateModel(
            name="SystemNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("video", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("picture", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("click_num", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "system_notice",
            },
        ),
        migrations.CreateModel(
            name="VideoPhotography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("video", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("picture", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("click_num", models.IntegerField(default=0)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "video_photography",
            },
        ),
    ]
