# Generated by Django 5.1.4 on 2024-12-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lcs1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("video", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("picture", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "introduction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("click_num", models.IntegerField(default=0)),
                ("code_block", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
    ]
