# Generated by Django 5.1.4 on 2024-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysuser",
            name="menu_ids",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
